title: "Arq. [Tu Nombre] | Project Management Portfolio"
description: "Especialista en Control de Gestión (CDG) y Coordinación de Obras Civiles"
remote_theme: pages-themes/architect@v0.2.0
google_analytics: 
show_downloads: false
