title: "Juan Manuel Sempio | Architect, PM & Developer"
description: "Project Management, Urban Planning, and Tech Solutions for Construction"
logo: /autor.jpeg
remote_theme: pages-themes/minimal@v0.2.0
show_downloads: false
